# Generated by Django 4.2.15 on 2024-08-16 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveltask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traveltask',
            name='transportation',
            field=models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Bus', 'Bus'), ('Own Vehicle', 'Own Vehicle'), ('Bicycle', 'Bicycle'), ('Boat', 'Boat'), ('Other', 'Other')], default='Flight', max_length=12),
        ),
        migrations.AddField(
            model_name='traveltask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
