# Generated by Django 4.2.15 on 2024-08-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_tasks', '0002_traveltask_created_at_traveltask_transportation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traveltask',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='traveltask',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
